import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { ClientStuff } from "./client-stuff"

const sans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${sans.variable} antialiased`}>
        <div className="p-10 space-y-4">
          <div>
            <h1 className="text-2xl font-bold">Next.JS Initial Load</h1>
            <p>
              This is a test of the initial load of a Next.JS application. Popovers sometimes not interactable on initial load.
            </p>
            <ClientStuff />
          </div>
          <div className="flex gap-4 border-b">
            <Button asChild variant="link">
              <Link href="/">page 1</Link>
            </Button>
            <Button asChild variant="link">
              <Link href="/2">page 2</Link>
            </Button>
          </div>
          {children}
        </div>
      </body>
    </html>
  )
}
